Many more changes
1. Pseudowinter/PseudoChaser - gap audit should not fire if gap is zero minutes. 

2. PseudoChaser/PseudoWinter/EverWinter - Fixed over-counting losses due to loss absorption PnL card roll-up. 

3. PseudoChaser/Pseudowinter/EverWinter - Fixed insufficient saved margin for SW spam. 

4. Pseudowinter/PseudoChaser/EverWinter - Max total conditionals at a time is 6, if already at 6 or more bots will not create more SW stages. 

5. PseudoChaser1️⃣/Pseudowinter/EverWinter - Adjusted Debt system, if EDa TP would be less than config entry TP in normal phase or reduce phase TP in reduce phase, then use normal TP or reduce TP respectively. 

6. EverWinter/PseudoWinter/PseudoChaser - Changed reduce phase position card badge. 

7. Pseudowinter/PseudoChaser/(maybe) EverWinter - Funding settled activity log messages needs to be rolled up if Multiple fire simultaneously. 

8. Pseudowinter - fixed "Cycle error:  this setTP is not a function" 

9. Pseudowinter/EverWinter/PseudoChaser - Fixed routine crowding and overall lag. 

10. PseudoChaser - Adjusted FUN, used over-extension history as entry criteria. Used positive funding rates instead of negative. 

11. PseudoChaser - Erased adv ft. 

12. PseudoChaser - Fixed slow start-up and scans.